context:
  version: 0.2.1

package:
  name: fcp-rust
  version: ${{ version }}

source:
  url: https://github.com/Svetlitski/fcp/archive/v${{ version }}.tar.gz
  sha256: e835d014849f5a3431a0798bcac02332915084bf4f4070fb1c6914b1865295f2

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script: |
      fcp --help 2>&1 | grep -q "fcp \[OPTIONS\] SOURCE DESTINATION_FILE"

about:
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Significantly faster alternative to the classic Unix cp(1) command
  homepage: https://github.com/Svetlitski/fcp
  repository: https://github.com/Svetlitski/fcp

extra:
  recipe-maintainers:
    - danielnachun
